### ISSUE TITLE
Invalid syntax for python3

### ISSUE THREAD

**Issue by stacysimpson** [kaltura-vpaas/webcasting-app-python#6]
This line: https://github.com/kaltura-vpaas/webcasting-app-python/blob/master/create.py#L30

`Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from create import Livestream
  File ".../webcasting-app-python/create.py", line 30
    live_stream_entry.conversionProfileId = 0000000git
                                                     ^
SyntaxError: invalid syntax`

**Comment by stacysimpson** [comment]
For the record, all 0's doesn't work either.

`KalturaClient.exceptions.KalturaException: Conversion profile id "0" not found (CONVERSION_PROFILE_ID_NOT_FOUND)`
